
import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aqleema
 */
public class Home1 extends javax.swing.JFrame {
    
    public int onlineStatus=0;
    
    Connection con;
    Statement sp;
    ResultSet rs;
    
    /**
     * Creates new form Home1
     */
    public Home1() {
        try{
        establishConnection();
        }catch(Exception e){
            System.out.println(e);
        }
        
        try{
            
            String que="delete from onlineStatus";
            sp=con.prepareStatement(que);
            sp.executeUpdate(que);
        }catch(Exception e){
            System.out.println(e);
        }
        
        
        
        
         try{
        //String que="Update onlineStatus set isOnline=0 where id=1 ";
        //     String que="delete from onlineStatus";
          String que="insert into onlineStatus (isOnline, id,username) values (0,1," + "'" + " " + "'" + ")";   
          sp=con.prepareStatement(que);
            sp.executeUpdate(que);
        }catch(Exception e){
            System.out.println("Hi 2.0 " + e);                                                                                                                                                                                                   
        }
        
        
        initComponents();
    }
      public void establishConnection()
             throws ClassNotFoundException, SQLException
    {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flight_management?zeroDateTimeBehavior=convertToNull", "root","");
        sp=(Statement) con.createStatement();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        reserveSeatBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        cancelSeatBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reserveSeatBtn.setText("Reserve seat");
        reserveSeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSeatBtnActionPerformed(evt);
            }
        });

        jButton1.setText("View Time Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        adminBtn.setText("Login as Admin");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });

        cancelSeatBtn.setText("Cancel seat");
        cancelSeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSeatBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel2.setText("A&M Airlines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360)
                        .addComponent(reserveSeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cancelSeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360)
                        .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveSeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cancelSeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timeTable tt= new timeTable();
        tt.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void reserveSeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSeatBtnActionPerformed
        // TODO add your handling code here:
        
        String flag="0";
        int f=0;
        
        try{
        String query= "select * from onlineStatus ";
        sp=con.prepareStatement(query);
        rs=sp.executeQuery(query);
        rs.next();
        String admin = "" + rs.getObject("username");
        if(admin == "admin")
        {
            JOptionPane.showMessageDialog(null, "Admin can not reserve the seat."  ,"Access denied", JOptionPane.ERROR_MESSAGE);
                    
        }
        flag= "" + rs.getObject("isOnline");
        f=Integer.parseInt(flag);
            System.out.println(flag);
        }catch(Exception e)
        {
            System.out.println("WERE THE?!" + e);
        }
      
        System.out.println(f);
        
        if(f==0)
        {
            LoginFirst lf = new LoginFirst();
            lf.setVisible(true);
        }
        else
        {
            reservation r=new reservation(this);
            r.setVisible(true);
        }
        
//        JPopupMenu p=new JPopupMenu();
//        p.setLocation(300, 300);
//        p.setPopupSize(100, 100);
//        p.add("Login first");
//        p.setVisible(true);
          
        
    }//GEN-LAST:event_reserveSeatBtnActionPerformed

    private void cancelSeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSeatBtnActionPerformed
        // TODO add your handling code here:
         String flag="0";
        int f=0;
        
        try{
        String query= "select * from onlineStatus ";
        sp=con.prepareStatement(query);
        rs=sp.executeQuery(query);
        rs.next();
        flag= "" + rs.getObject("isOnline");
        f=Integer.parseInt(flag);
            System.out.println(flag);
        }catch(Exception e)
        {
            System.out.println("WERE THE?!" + e);
        }
      
        System.out.println(f);
        
        if(f==0)
        {
            LoginFirst lf = new LoginFirst();
            lf.setVisible(true);
        }
        else
        {
            cancelation c=new cancelation();
            c.setVisible(true);
        }
        
        
        
        
    }//GEN-LAST:event_cancelSeatBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        
        
        String admin="";
        try{
        String query= "select * from onlineStatus ";
        sp=con.prepareStatement(query);
        rs=sp.executeQuery(query);
        if(rs.next()){
        admin = "" + rs.getObject("username");
        }
         }catch(Exception e){
           
        }
        if(admin== "admin")
        {
            adminForm af=new adminForm();
            af.setVisible(true);
            this.dispose();
        }
        else{     
        
        adminLogin al=new adminLogin();
        al.setVisible(true);
        }
    }//GEN-LAST:event_adminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton cancelSeatBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton reserveSeatBtn;
    // End of variables declaration//GEN-END:variables
}
